---
- name: install desktop (xfce) packages
  apt:
    name:
      - xfce4
      - x11-apps
      - xauth
      - xterm
      - xfce4-terminal
      - fontconfig
      # note: pulseaudio must be installed before nomachine
      #       (see link below for more information)
      # https://www.vultr.com/docs/setup-nomachine-nx-on-ubuntu
      - pulseaudio
      # pavucontrol is required by xfce volume control applet
      - pavucontrol
    # avoid apport (breaks idempotency on bionic)
    install_recommends: false
  register: nx_desktop_packages
...
