---
- name: open nxserver ports for all in ufw
  ufw:
    rule: allow
    port: "{{ item |string }}"
    ## allow both tcp (main) and udp (multimedia)
    # proto: tcp
  no_log: "{{ hide_secrets |bool }}"
  loop: "{{ lin_nxserver_ports }}"
  ## workaround for ufw failures on xenial github runners
  register: ufw_result
  until: ufw_result is successful
  when: lin_firewall == 'ufw'

- name: open nxserver ports for all in ferm
  ferm_port:
    port: "{{ lin_nxserver_ports }}"
    zone: external
    solo_zone: true
    comment: nxserver
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
        and lin_nxserver_direct |bool

- name: block nxserver from external ferm hosts but open for internals
  ## Adding port in two domains at once and removing from external.
  ## The solo flag can't do that so use loop as a workaround.
  ferm_port:
    port: "{{ lin_nxserver_ports }}"
    zone: "{{ item }}"
    solo_zone: false
    state: "{{ 'absent' if item == 'external' else 'present' }}"
    comment: nxserver
  loop: [internal, blocked, external]
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
        and not lin_nxserver_direct |bool
...
