---
- setup:
  become: no

- name: install nxserver
  import_tasks: nxserver.yml
  become: yes
  tags: nx_server

- name: authorize user
  import_tasks: user.yml
  become: no
  tags: nx_user

- name: install window manager
  import_tasks: winman.yml
  become: yes
  tags: nx_wmanager

- name: setup swap space
  import_tasks: swap.yml
  become: yes
  when: lin_swap_enable | bool
  tags: nx_swap

- name: reboot after fresh install to work around problems with dbus
  reboot:
    pre_reboot_delay: 5
  become: yes
  when: nx_nxserver_packages is changed and nx_winman_packages is changed
  tags: nx_reboot
...
