---
- name: refresh facts as non root
  setup:
  become: false

- name: most steps require elevated privileges
  block:
    - name: install desktop environment (should come before nomachine)
      import_tasks: desktop.yml
      tags: lin_nx_desktop

    - name: install nxserver
      import_tasks: nxserver.yml
      tags: lin_nx_server

    - name: enable audio in nxserver
      import_tasks: audio.yml
      tags: lin_nx_audio

    - name: setup swap space
      import_tasks: swap.yml
      when: lin_swap_enable |bool
      tags: lin_nx_swap
  become: true
  tags:
    - lin_nx_root
    - lin_nx_all

- name: authorize user
  import_tasks: user.yml
  become: false
  tags:
    - lin_nx_user
    - lin_nx_all

- name: reboot to work around dbus issues
  block:
    - name: reboot after fresh install (warnings are ok)
      reboot:
        pre_reboot_delay: 20
      when: nx_nxserver_packages is changed
            and nx_desktop_packages is changed
            and allow_reboot |bool

    - name: ask user to reboot
      debug:
        msg: "please reboot {{ inventory_hostname }} manually"
      when: nx_nxserver_packages is changed
            and nx_desktop_packages is changed
            and not allow_reboot |bool
  become: true
  tags:
    - lin_nx_reboot
    - lin_nx_all
...
