---
- name: gather installed nxserver version
  # should ignore linter warning about pipefail here
  # it's perfectly valid to fail if package is not installed
  # noqa 306
  shell: dpkg --list nomachine | awk '/^ii / {print $3}'
  changed_when: false
  register: old_ver

- name: derive new nxserver version
  set_fact:
    new_ver: "{{ lin_nxserver_deb_url | regex_replace('^.*?_([\\d\\._]{3,})_.*$', '\\1') | replace('_', '-') }}"

- name: install nxserver package
  apt:
    deb: "{{ lin_nxserver_deb_url }}"
  when: old_ver.stdout != new_ver
  register: nx_nxserver_packages
  # fix intermittent network errors on .ru boxes
  until: "'timed out' not in nx_nxserver_packages.msg |default('')"

- name: open nxserver port
  ufw:
    rule: allow
    port: "{{ lin_nxserver_port }}"
    # allow both tcp (main) and udp (multimedia)
    #proto: tcp
  no_log: true
...
