---
- name: install desktop environment (should come before nomachine)
  import_tasks: desktop.yml
  tags: lin_nx_desktop

- name: install nxserver
  import_tasks: nxserver.yml
  when: lin_nxserver_enabled |bool
  tags: lin_nx_server

- name: configure firewall for nxserver
  import_tasks: firewall.yml
  tags: lin_nx_firewall

- name: enable audio in nxserver
  import_tasks: audio.yml
  when: lin_nxserver_enabled |bool
  tags: lin_nx_audio
...
